config/routes.rb
Rails.application.routes.draw do

  resources :goals
  resources :incomes do
    resources :income_payments
  end

  resources :home
  get 'dashboard/show'
  get 'home/expired'

  resources :categories
  resources :data_points

  resources :expenses do
    resources :expense_payments
  end

  devise_for :accounts
  root 'home#index'

end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :account
  belongs_to :category
  
  has_many :income_payments

  validates :income_source, presence: true
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :authenticate_account!
  before_action :set_income, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit, :create, :update]
  

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = current_account.incomes.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = current_account.incomes.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end
  
    def set_categories
      @categories = Category.all.collect{|c| [c.title, c.id] }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:income_source, :category_id, :gross_income, :net_income, :bank_account)
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :income_source %><br>
    <%= f.text_area :income_source %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category_id, @categories, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :gross_income %><br>
    <%= f.text_field :gross_income %>
  </div>
  <div class="field">
    <%= f.label :net_income %><br>
    <%= f.text_field :net_income %>
  </div>
  <div class="field">
    <%= f.label :bank_account %><br>
    <%= f.text_area :bank_account %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form' %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice" class="row"><%= notice %></p>
<div class="col-sm-12">
<h1>Incomes</h1>
<p class="col-sm-12">
  <%= link_to 'New Income', new_income_path, class: "btn btn-primary" %>
</p>

  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Income Source</th>
        <th>Income Amount</th>
        <th>Category</th>
        <th>Bank Account</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @incomes.each do |income| %>
        <tr>
          <td><%= income.income_source %></td>
          <td></td>
          <td>
            <% if income.category %>
              <%= income.category.title %>
            <% else %>
              None
            <% end %>
          </td>
          <td><%= income.bank_account %></td>
          <td><%= link_to 'Show', income %></td>
          <td><%= link_to 'Edit', edit_income_path(income) %></td>
          <td><%= link_to 'Manage Payments', income_income_payments_path(income) %></td>
          <td><%= link_to 'Delete', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form' %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Income Source:</strong>
  <%= @income.income_source %>
</p>

<p>
  <strong>Category:</strong>
  <% if @income.category %>
    <%= @income.category.title %>
  <% else %>
    None
  <% end %>
</p>

<p>
  <strong>Gross Income:</strong>
  <%= @income.gross_income %>
</p>

<p>
  <strong>Net Income:</strong>
  <%= @income.net_income %>
</p>

<p>
  <strong>Bank Account:</strong>
  <%= @income.bank_account %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>