config/routes.rb
Rails.application.routes.draw do

  resources :goals
  resources :incomes do
    resources :income_payments
  end

  resources :home
  get 'dashboard/show'
  get 'home/expired'

  resources :categories
  resources :data_points

  resources :expenses do
    resources :expense_payments
  end

  devise_for :accounts
  root 'home#index'

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_account!
  before_action :set_expense, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit, :create, :update]


  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = current_account.expenses
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = current_account.expenses.build(expense_params)


    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = current_account.expenses.find(params[:id])
    end

    def set_categories
      @categories = Category.all.collect{|c| [c.title, c.id] }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:name, :category_id, :amount, :due_date, :payment_date, :late_fee, :apr, :paid)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category_id, @categories, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :payment_date %><br>
    <%= f.date_select :payment_date %>
  </div>
  <div class="field">
    <%= f.label :late_fee %><br>
    <%= f.text_field :late_fee %>
  </div>
  <div class="field">
    <%= f.label :apr %><br>
    <%= f.text_field :apr %>
  </div>
  <div class="field">
    <%= f.label :paid %><br>
    <%= f.check_box :paid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<div class="row">
  <div class="col-sm-12">

<h1>Expenses</h1>
<p class="col-sm-12">
  <%= link_to 'New Expense', new_expense_path, class: "btn btn-primary" %>
</p>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Amount</th>
      <th>Due Date</th>
      <th>Payment Date</th>
      <th>Late Fee</th>
      <th>APR</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.name %></td>
        <td>
          <% if expense.category %>
            <%= expense.category.title %>
          <% else %>
            None
          <% end %>
        </td>
        <td><%= number_to_currency (expense.amount) %></td>
        <td><%= expense.due_date.strftime("%m/%d/%Y") %></td>
        <td><%= expense.payment_date.strftime("%m/%d/%Y") %></td>
        <td><%= expense.late_fee %></td>
        <td><%= expense.apr %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Manage Payments', expense_expense_payments_path(expense) %></td>
        <td><%= link_to 'Delete', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  </tbody>
</table>

  </div>
</div>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @expense.name %>
</p>

<% if @expense.category %>
  <p>
    <strong>Category:</strong>
    <%= @expense.category.title %>
  </p>
<% else %>
  <p>
    None
  </p>
<% end %>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @expense.due_date %>
</p>

<p>
  <strong>Payment date:</strong>
  <%= @expense.payment_date %>
</p>

<p>
  <strong>Late fee:</strong>
  <%= @expense.late_fee %>
</p>

<p>
  <strong>APR:</strong>
  <%= @expense.apr %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @expense.paid %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>