config/routes.rb
Rails.application.routes.draw do

  resources :goals
  resources :incomes do
    resources :income_payments
  end

  resources :home
  get 'dashboard/show'
  get 'home/expired'

  resources :categories
  resources :data_points

  resources :expenses do
    resources :expense_payments
  end

  devise_for :accounts
  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Budget Companion</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container-fluid">


      <nav class="nav navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app_navbar" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          <a class="navbar-brand" href="/">Budget Companion</a>
        </div>
          <div class="collapse navbar-collapse" id="app_navbar">
            <ul class="nav navbar-nav navbar-left">
            <% if account_signed_in? %>
              <li><%= link_to "Dashboard", dashboard_show_path %></li>
              <li><%= link_to "View Incomes", incomes_path %></li>
              <li><%= link_to "View Expenses", expenses_path %></li>
              <li><%= link_to "View Goals", goals_path %></li>
              <li><%= link_to "My Account", edit_account_registration_path %></li>
              <li><a href="https://en.gravatar.com/support/what-is-gravatar/"><%= image_tag current_account.gravatar_url(size: 20) %></a></li>
            <% end %>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if account_signed_in? %>
              <li><%= link_to "Sign Out", destroy_account_session_path, method: :delete %> </li>
            <% else %>
              <li><%= link_to "Sign in", new_account_session_path %> </li>
            <% end %>
          </ul>
      </nav>

      <div class="row">
        <div class="col-sm-12">
          <% if notice %>
            <div class="alert alert-success" role="alert">
              <p><%= notice %></p>
            </div>
          <% end %>
          <% if alert %>
            <div class="alert alert-warning" role="alert">
              <p><%= alert %></p>
            </div>
          <% end %>
        </div>
      </div>
      <%= yield %>

      <footer class="row">
         <div class="col-sm-12">
          <small>Copyright &copy; <%=Date.today.year %></small>
         </div>
      </footer>
    </div><!--div container-->
   
  </body>
</html>